### ISSUE TITLE
Incompatibility with floodgate on fabric 1.20.2

### ISSUE THREAD

**Issue by RealKomander** [OKTW-Network/FabricProxy-Lite#65]
To replicate, download geyesrMC, floodgate and fabric proxy lite 2.7.0 on fabric 1.20.2

Getting this awfully looking error:
[latest.log](https://github.com/OKTW-Network/FabricProxy-Lite/files/13226881/latest.log)

Please help, those bytecodes haunt me in my dreams

**Comment by james58899** [comment]
This is not a bug of FabricProxy-Lite, please report it to floodgate.

**Comment by RealKomander** [comment]
They told me that it's not a floodgate issue and that I should report it to you!

**Comment by james58899** [comment]
This mod only uses FabricAPI, and there are no errors related to FabricProxy-Lite in the log.

**Comment by onebeastchris** [comment]
The issue shouldn't be within floodgate-fabric, but rather a floodgate dependency (adventure-platform-fabric by kyori).

When asked in their discord server (https://discord.gg/MMfhJ8F), this is what they replied with:

![Screenshot_2023-11-19-17-14-33-85_572064f74bd5f9fa804b05334aa4f912.jpg](https://github.com/OKTW-Network/FabricProxy-Lite/assets/105284508/121ec616-5f06-4796-b9fb-2e83e4307900)

Please feel free to get in touch via the GeyserMC discord if there's more info from our side that's needed.

**Comment by james58899** [comment]
This mod does not touch class_2889, it may be modified by FabricAPI, which means that floodgate's dependency breaks FabricAPI.

Since this issue is unlikely to be caused by FabricProxy-Lite, I can't fix it unless someone points out what's wrong.

**Comment by RealKomander** [comment]
So what then, what is causing the issue?

**Comment by onebeastchris** [comment]
We're looking into in on our side - so is kyori, since their project is for some reason the one that is throwing

**Comment by RealKomander** [comment]
great, thanks for that

**Comment by onebeastchris** [comment]
Sorry; this was a faulty floodgate mixin (https://github.com/GeyserMC/Floodgate-Fabric/pull/112) that wasn't properly ported to 1.20.2
Reason it was only happening when FabricProxy-Lite was installed - we only apply this particular mixin when it's present, since it's needed for floodgate-velocity <-> floodgate-fabric communication. FabricProxy-Legacy already bundle such a mixin, so this wasnt happening with that mod. 

Not sure why the error was blaming kyori's adventure-platform-fabric instead of floodgate though; that made me think it was an issue with the library.

Huge thanks to you and zml for helping debug this :)
